// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "N1ktarchik/Board_of_issues/internal/core/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeskRepository is a mock of DeskRepository interface.
type MockDeskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeskRepositoryMockRecorder
	isgomock struct{}
}

// MockDeskRepositoryMockRecorder is the mock recorder for MockDeskRepository.
type MockDeskRepositoryMockRecorder struct {
	mock *MockDeskRepository
}

// NewMockDeskRepository creates a new mock instance.
func NewMockDeskRepository(ctrl *gomock.Controller) *MockDeskRepository {
	mock := &MockDeskRepository{ctrl: ctrl}
	mock.recorder = &MockDeskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeskRepository) EXPECT() *MockDeskRepositoryMockRecorder {
	return m.recorder
}

// ChangeDesksData mocks base method.
func (m *MockDeskRepository) ChangeDesksData(ctx context.Context, deskUpdate *domain.Desk, requesterID uuid.UUID) (*domain.Desk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeDesksData", ctx, deskUpdate, requesterID)
	ret0, _ := ret[0].(*domain.Desk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeDesksData indicates an expected call of ChangeDesksData.
func (mr *MockDeskRepositoryMockRecorder) ChangeDesksData(ctx, deskUpdate, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeDesksData", reflect.TypeOf((*MockDeskRepository)(nil).ChangeDesksData), ctx, deskUpdate, requesterID)
}

// ConnectUserToDesk mocks base method.
func (m *MockDeskRepository) ConnectUserToDesk(ctx context.Context, userID, deskID uuid.UUID, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectUserToDesk", ctx, userID, deskID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectUserToDesk indicates an expected call of ConnectUserToDesk.
func (mr *MockDeskRepositoryMockRecorder) ConnectUserToDesk(ctx, userID, deskID, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectUserToDesk", reflect.TypeOf((*MockDeskRepository)(nil).ConnectUserToDesk), ctx, userID, deskID, password)
}

// CreateDesk mocks base method.
func (m *MockDeskRepository) CreateDesk(ctx context.Context, desk *domain.Desk) (*domain.Desk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDesk", ctx, desk)
	ret0, _ := ret[0].(*domain.Desk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDesk indicates an expected call of CreateDesk.
func (mr *MockDeskRepositoryMockRecorder) CreateDesk(ctx, desk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDesk", reflect.TypeOf((*MockDeskRepository)(nil).CreateDesk), ctx, desk)
}

// DeleteDesk mocks base method.
func (m *MockDeskRepository) DeleteDesk(ctx context.Context, userUUID, deskUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesk", ctx, userUUID, deskUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDesk indicates an expected call of DeleteDesk.
func (mr *MockDeskRepositoryMockRecorder) DeleteDesk(ctx, userUUID, deskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesk", reflect.TypeOf((*MockDeskRepository)(nil).DeleteDesk), ctx, userUUID, deskUUID)
}

// GetAllUsersDesks mocks base method.
func (m *MockDeskRepository) GetAllUsersDesks(ctx context.Context, userUUID uuid.UUID) ([]domain.Desk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsersDesks", ctx, userUUID)
	ret0, _ := ret[0].([]domain.Desk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsersDesks indicates an expected call of GetAllUsersDesks.
func (mr *MockDeskRepositoryMockRecorder) GetAllUsersDesks(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsersDesks", reflect.TypeOf((*MockDeskRepository)(nil).GetAllUsersDesks), ctx, userUUID)
}
